version: 2.1
orbs:
  node: circleci/node@5
  jq: circleci/jq@3.0.1
jobs:
  build:
    executor: node/default
    working_directory: ~/angular-interview-task
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build:production
      - persist_to_workspace:
            root: ~/angular-interview-task
            paths:
                - .
  deploy:
    working_directory: ~/angular-interview-task
    docker:
      - image: cimg/base:2024.02
    steps:
      - attach_workspace:
            at: ~/angular-interview-task
      - run:
          command: |
            mkdir -p ~/.ssh
            DNS_RECORD=$(curl -sX GET "https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/dns_records/?name=$CF_HOST_NAME" -H "Authorization: Bearer $CF_API_KEY"  | jq -r '.result[] | select(.name == "'$CF_HOST_NAME'")')
            CURRENT_DNS_VALUE=$(echo $DNS_RECORD | jq -r '.content')
            ssh-keyscan $CURRENT_DNS_VALUE >> ~/.ssh/known_hosts
      - run:
          command: |
            DNS_RECORD=$(curl -sX GET "https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/dns_records/?name=$CF_HOST_NAME" -H "Authorization: Bearer $CF_API_KEY"  | jq -r '.result[] | select(.name == "'$CF_HOST_NAME'")')
            CURRENT_DNS_VALUE=$(echo $DNS_RECORD | jq -r '.content')
            echo $SSH_PRIVATE_KEY > private-key
            sed -i '' -e '$a\' private-key
            chmod 400 private-key
            scp -rv -i private-key ./dist/angular-interview-task/* $SSH_USER@$CURRENT_DNS_VALUE:apps/angular-interview-task
workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
