version: 2.1
orbs:
  node: circleci/node@5
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build:production
  deploy:
    docker:
      - image: cimg/base:2024.02
    steps:
      - add_ssh_keys
      - run:
          command: |
            scp -r ./dist/angular-interview-task/*.* $SSH_USER@$SSH_HOST:Websites/angularinterviewtask
workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
