version: 2.1
orbs:
  node: circleci/node@5
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build --configuration production
  deploy:
  - run:
      command: ls
workflows:
  build-and-test:
    jobs:
      - build
      - deploy:
          requires:
            - build
