version: 2.1
orbs:
  node: circleci/node@5
jobs:
  build:
    executor: node/default
    working_directory: /
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build:production
      - run:
          command: ls
  deploy:
    working_directory: /
    docker:
      - image: cimg/base:2024.02
    steps:
      - run:
          command: ls
      - run:
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
            - "SHA256:lakOTEoV2u8yOq2gKa0n5nZzlRlnVgLTI29394kSxAw"
      - run:
          command: |
            scp -r ./dist/angular-interview-task/*.* $SSH_USER@$SSH_HOST:Websites/angularinterviewtask
workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
