version: 2.1
orbs:
  node: circleci/node@5
jobs:
  build:
    executor: node/default
    working_directory: ~/angular-interview-task
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build:production
      - persist_to_workspace:
            root: ~/angular-interview-task
            paths:
                - .
  deploy:
    working_directory: ~/angular-interview-task
    docker:
      - image: cimg/base:2024.02
    steps:
      - attach_workspace:
            at: ~/angular-interview-task
      - run:
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan -6v $SSH_HOST >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
            - "SHA256:lakOTEoV2u8yOq2gKa0n5nZzlRlnVgLTI29394kSxAw"
      - run:
          command: |
            scp -r ./dist/angular-interview-task/* $SSH_USER@$SSH_HOST:apps/angular-interview-task
workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
