version: 2.1
orbs:
  node: circleci/node@5
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build:production
  deploy:
    executor: node/default
    steps:
      - run:
          command: ls
workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
